### ISSUE TITLE
Do not error on |base64offset|contains

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#313]
@fukusuket 
Now that Hayabusa v2.2.2 supports `|base64offset|contains`, we will need to not produce errors when converting rules. Can you write an exception for `|base64offset|contains` in `hayabusa.py` so that we can add these rules?

**Comment by fukusuket** [comment]
@YamatoSecurity @hitenkoku 
After investigating, I found the following🤔 

Unfortunately, it seems difficult to support `base64offset|contains` just by modifying `hayabusa.py` and `convert.py` :(

Current `convert.py` error message is as follows. 
```
[WARNING ] Conversion of "proc_creation_win_powershell_base64_frombase64string.yml" failed.
command: ['python3', './tools/sigmac', '-t', 'hayabusa', '-c', './tools/config/generic/windows-audit.yml', '-c', './tools/config/generic/windows-services.yml', '--defer-abort', './rules/windows/process_creation/proc_creation_win_powershell_base64_frombase64string.yml']
An unsupported feature is required for this Sigma rule (rules/windows/process_creation/proc_creation_win_powershell_base64_frombase64string.yml):
```

The error **An unsupported feature is required for this Sigma rule** is due to the handling of `multiple pipes` and `base64offset modifier` on the **sigmac side error**, which cannot be controlled by `hayabusa.py` side.

**Comment by fukusuket** [comment]
I think the solution for now is ... (I can't think of a good way to fix it at the moment... :( )

- Fork `sigmac` and customize 
  -  Because it deprecated the end of 2022...
- Use `pySigma` instead of `sigmac`
  - I'm not sure it will work, but it looks like there might be better support for handling multiple pipes. I'll investigate.

Sorry.. Either way, It seems difficult to include in version 2.2.2🤔

If you have any good ideas, please let me know :)

**Comment by fukusuket** [comment]
Looking at the test case below, it looks like `PySigma` has support for `base64offset|contains` conversion.
- https://github.com/SigmaHQ/pySigma/blob/v0.9.3/tests/test_validators.py#L445-L457

**Comment by hitenkoku** [comment]
@fukusuket Thank you for looking into this.
PySigma needs to be made using a different mechanism called cookiecutter.

The only backend for pySigma is currently splunk, and it is a bit hard to find a few references. href: ttps://github.com/SigmaHQ/pySigma-backend-splunk

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much for looking into this. That is unfortunate..
As a temporary solution, since there are only several rules that use `base64offset|contains`, I can manually convert them into hayabusa rules and host them in the hayabusa folder in the rules dir. I probably won't be able to update them frequently but it is better than not having the rules at all.

**Comment by fukusuket** [comment]
I sent an issue report and PR to the Sigma repository side :)
- https://github.com/SigmaHQ/sigma/issues/4063
- https://github.com/SigmaHQ/sigma/pull/4064

**Comment by fukusuket** [comment]
I creaated a PR. If the Sigma team can merge the PR, we can remove the rule.py...
- https://github.com/SigmaHQ/sigma/pull/4071

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much! I will re-open this issue for now then.

**Comment by fukusuket** [comment]
Unfortunately [the PR](https://github.com/SigmaHQ/sigma/pull/4071) was not accepted :(
However, since the upstream error has been resolved, it should be possible to implement it without using rule.py, so I will try it!

**Comment by YamatoSecurity** [comment]
Closed with https://github.com/Yamato-Security/hayabusa-rules/pull/315
